// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzllesfuxjqbnevwbkao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bGxlc2Z1eGpxYm5ldndia2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzM2MzcsImV4cCI6MjA2OTgwOTYzN30.iGlcRD9eqaTFE3kQfp0qRgf2pHlDw8xDAlvhNeHxY7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});